spring:
  application:
    name: coffeechat

  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin
      database: coffeechat
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    exchange:
      chat: chat.exchange
      dlx: chat.dlx.exchange
    routing-key:
      message: chat.message.send
      dlq: chat.dlq
    queue:
      dlq: chat.queue.dlq
    listener:
      simple:
        concurrency: 3
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 500
          multiplier: 1.0
          max-interval: 1000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      access: read-only